### ISSUE TITLE
gsutil version

### ISSUE THREAD

**Issue by erikbr01** [kpertsch/rlds_dataset_mod#1]
Hi Karl, thanks for providing this! Quick heads up for the gsutil version, the version currently available through apt (2.* for Ubuntu Focal) doesn't have the -m option, a newer one will have to be used. Perhaps it could be added to the conda env or added as a note in the README. Cheers!

**Comment by kpertsch** [comment]
Thanks for the heads-up -- added a line in the README to install following the install instructions here: https://cloud.google.com/storage/docs/gsutil_install
